import { Plan } from "../_mockInterfaces/plan";
import { modulesData } from "./modulesData";
import { mockPeriodTypes } from "./periodTypesData";


export const mockPlans: Plan[] = [
    {
        id: '1',
        name: 'Free Trial',
        description: 'Try our service for free for 30 days',
        slotPrice: 0,
        slotDiscountPrice: 0,
        planDetails: ['Full Access', 'Unlimited Storage', 'Round the clock support'],
        currencyId: 'USD',
        currency: {
            id: 'USD',
            code: 'USD',
            name: 'US Dollar',
            symbol: '$',
            createdAt: '2023-06-01T00:00:00.000Z',
            updatedAt: '2023-06-01T00:00:00.000Z',
            deletedAt: '',
            createdBy: 'system',
            updatedBy: 'system',
            deletedBy: '',
        },
        monthlyPrice: 0,
        quarterlyPrice: 0,
        yearlyPrice: 0,
        customPrice: 0,
        isFree: true,
        isPublic: true,
        successorPlanId: '',
        successorPlan: null,
        lateFeeAmount: 0,
        lateFeeDescription: '',
        invoiceGenerationDaysBefore: 12,
        gracePeriodDays: 0,
        trialDurationDays: 30,
        maxTrialSlots: 1,
        modules: [modulesData[1]],
        periodTypes: [mockPeriodTypes[1]]
    },
    {
        id: '2',
        name: 'Basic Plan',
        description: 'Our basic plan for small businesses',
        slotPrice: 10,
        slotDiscountPrice: 8,
        planDetails: ['Full Access', 'Unlimited Storage', 'Round the clock support', 'Advanced analytics','Customizable workflows'],
        currencyId: 'USD',
        currency: {
            id: 'USD',
            code: 'USD',
            name: 'US Dollar',
            symbol: '$',
            createdAt: '2023-06-01T00:00:00.000Z',
            updatedAt: '2023-06-01T00:00:00.000Z',
            deletedAt: '',
            createdBy: 'system',
            updatedBy: 'system',
            deletedBy: '',
        },
        monthlyPrice: 10,
        quarterlyPrice: 8,
        yearlyPrice: 6,
        customPrice: 0,
        isFree: false,
        isPublic: true,
        successorPlanId: '',
        successorPlan: null,
        lateFeeAmount: 5,
        lateFeeDescription: 'Late fee for Basic Plan',
        invoiceGenerationDaysBefore: 5,
        gracePeriodDays: 5,
        trialDurationDays: 0,
        maxTrialSlots: 0,
        modules: [modulesData[2]],
        periodTypes: [mockPeriodTypes[2]],
    },
    {
        id: '3',
        name: 'Standard Plan',
        description: 'Our standard plan for growing businesses',
        slotPrice: 20,
        slotDiscountPrice: 15,
        planDetails: ['Full Access', 'Unlimited Storage', 'Round the clock support', 'Advanced analytics','Customizable workflows', 'Dedicated account manager'],
        currencyId: 'USD',
        currency: {
            id: 'USD',
            code: 'USD',
            name: 'US Dollar',
            symbol: '$',
            createdAt: '2023-06-01T00:00:00.000Z',
            updatedAt: '2023-06-01T00:00:00.000Z',
            deletedAt: '',
            createdBy: 'system',
            updatedBy: 'system',
            deletedBy: '',
        },
        monthlyPrice: 20,
        quarterlyPrice: 15,
        yearlyPrice: 10,
        customPrice: 0,
        isFree: false,
        isPublic: false,
        successorPlanId: '',
        successorPlan: null,
        lateFeeAmount: 10,
        lateFeeDescription: 'Late fee for Standard Plan',
        invoiceGenerationDaysBefore: 10,
        gracePeriodDays: 10,
        trialDurationDays: 0,
        maxTrialSlots: 0,
        modules: [modulesData[3]],
        periodTypes: [mockPeriodTypes[3]]
    },
];