import { GrowthPlanCategory } from '@/types/tna/growthPlan';

const tech = true;
const soft = false;

const skill = (id: string, name: string, requiresEvidence = tech) => ({
  id,
  name,
  requiresEvidence,
  resources: [] as Array<{
    id: string;
    title: string;
    type: 'link' | 'youtube' | 'document' | 'course';
    url: string;
    videoId?: string | null;
    courseId?: string | null;
    courseName?: string | null;
  }>,
});

/** Fourteen skill categories with mock descriptions and skills for the prototype. */
export const GROWTH_PLAN_TAXONOMY_SEED: GrowthPlanCategory[] = [
  {
    id: 'cat-leadership',
    name: 'Leadership, Management & Strategy',
    description:
      'Build leadership, people management, and strategic decision-making skills for managers and team leads.',
    isMapped: true,
    skills: [
      skill('lead-f-1', 'Business fundamentals', soft),
      skill('lead-f-2', 'Organizational structure', soft),
      skill('lead-f-3', 'Communication skills', soft),
      skill('lead-f-4', 'Teamwork and collaboration', soft),
      skill('lead-f-5', 'Time management', soft),
      skill('lead-f-6', 'Goal setting', soft),
      skill('lead-f-7', 'Problem solving', soft),
      skill('lead-f-8', 'Emotional intelligence', soft),
      skill('lead-f-9', 'Professional communication', soft),
      skill('lead-p-1', 'People management', soft),
      skill('lead-p-2', 'Delegation', soft),
      skill('lead-p-3', 'Performance management', soft),
      skill('lead-p-4', 'Feedback and coaching', soft),
      skill('lead-p-5', 'Conflict management', soft),
      skill('lead-p-6', 'Meeting management', soft),
      skill('lead-p-7', 'Decision making', soft),
      skill('lead-p-8', 'Stakeholder management', soft),
      skill('lead-p-9', 'Team motivation', soft),
      skill('lead-p-10', 'Resource planning', soft),
      skill('lead-a-1', 'Strategic planning', soft),
      skill('lead-a-2', 'Change management', soft),
      skill('lead-a-3', 'Organizational development', soft),
      skill('lead-a-4', 'Business analysis', soft),
      skill('lead-a-5', 'Risk management', soft),
      skill('lead-a-6', 'Financial and budget management', soft),
      skill('lead-a-7', 'Cross-functional leadership', soft),
      skill('lead-a-8', 'Data-driven decision making', soft),
      skill('lead-a-9', 'Organizational performance', soft),
      skill('lead-a-10', 'Succession planning', soft),
      skill('lead-l-1', 'Corporate strategy', soft),
      skill('lead-l-2', 'Executive decision making', soft),
      skill('lead-l-3', 'Business transformation', soft),
      skill('lead-l-4', 'Organizational leadership', soft),
      skill('lead-l-5', 'Strategic resource allocation', soft),
      skill('lead-l-6', 'Culture building', soft),
      skill('lead-l-7', 'Executive communication', soft),
      skill('lead-l-8', 'Governance', soft),
      skill('lead-l-9', 'Innovation strategy', soft),
      skill('lead-l-10', 'Leadership development', soft),
    ],
  },
  {
    id: 'cat-product',
    name: 'Product Management & Project Management',
    description:
      'Develop product discovery, delivery, and project execution skills across the product lifecycle.',
    isMapped: true,
    skills: [
      skill('pm-f-1', 'Product management fundamentals', soft),
      skill('pm-f-2', 'Project management fundamentals', soft),
      skill('pm-f-3', 'Agile principles', soft),
      skill('pm-f-4', 'Scrum', soft),
      skill('pm-f-5', 'Requirements gathering', soft),
      skill('pm-f-6', 'Stakeholder identification', soft),
      skill('pm-f-7', 'User needs', soft),
      skill('pm-f-8', 'Problem definition', soft),
      skill('pm-f-9', 'Documentation', soft),
      skill('pm-f-10', 'Basic project planning', soft),
      skill('pm-p-1', 'PRD writing', soft),
      skill('pm-p-2', 'BRD writing', soft),
      skill('pm-p-3', 'User stories', soft),
      skill('pm-p-4', 'Acceptance criteria', soft),
      skill('pm-p-5', 'Product backlog management', soft),
      skill('pm-p-6', 'Sprint planning', soft),
      skill('pm-p-7', 'Roadmapping', soft),
      skill('pm-p-8', 'Prioritization', soft),
      skill('pm-p-9', 'User research', soft),
      skill('pm-p-10', 'Wireframing and prototyping', soft),
      skill('pm-p-11', 'Project scheduling', soft),
      skill('pm-p-12', 'Risk identification', soft),
      skill('pm-p-13', 'Stakeholder communication', soft),
      skill('pm-a-1', 'Product strategy', soft),
      skill('pm-a-2', 'Product discovery', soft),
      skill('pm-a-3', 'Product analytics', soft),
      skill('pm-a-4', 'Market research', soft),
      skill('pm-a-5', 'MVP definition', soft),
      skill('pm-a-6', 'Product-market fit', soft),
      skill('pm-a-7', 'Product roadmap strategy', soft),
      skill('pm-a-8', 'Advanced prioritization', soft),
      skill('pm-a-9', 'Business case development', soft),
      skill('pm-a-10', 'Project risk management', soft),
      skill('pm-a-11', 'Budget management', soft),
      skill('pm-a-12', 'Cross-functional delivery', soft),
      skill('pm-a-13', 'Change management', soft),
      skill('pm-a-14', 'Product lifecycle management', soft),
      skill('pm-l-1', 'Product portfolio strategy', soft),
      skill('pm-l-2', 'Business strategy', soft),
      skill('pm-l-3', 'Product vision', soft),
      skill('pm-l-4', 'Organizational product strategy', soft),
      skill('pm-l-5', 'Portfolio management', soft),
      skill('pm-l-6', 'Executive stakeholder management', soft),
      skill('pm-l-7', 'Product-led growth', soft),
      skill('pm-l-8', 'Strategic decision making', soft),
      skill('pm-l-9', 'Large-scale program management', soft),
      skill('pm-l-10', 'Product team leadership', soft),
    ],
  },
  {
    id: 'cat-software',
    name: 'Software Development & Engineering',
    description:
      'Grow engineering craft from fundamentals through architecture and technical leadership.',
    isMapped: true,
    skills: [
      skill('sw-f-1', 'Programming fundamentals'),
      skill('sw-f-2', 'Data structures'),
      skill('sw-f-3', 'Algorithms'),
      skill('sw-f-4', 'Object-oriented programming'),
      skill('sw-f-5', 'Git and version control'),
      skill('sw-f-6', 'Databases'),
      skill('sw-f-7', 'SQL'),
      skill('sw-f-8', 'APIs'),
      skill('sw-f-9', 'Debugging'),
      skill('sw-f-10', 'Software development lifecycle'),
      skill('sw-f-11', 'Basic testing'),
      skill('sw-p-1', 'Frontend development'),
      skill('sw-p-2', 'Backend development'),
      skill('sw-p-3', 'Full-stack development'),
      skill('sw-p-4', 'REST APIs'),
      skill('sw-p-5', 'Database design'),
      skill('sw-p-6', 'Authentication and authorization'),
      skill('sw-p-7', 'Software architecture fundamentals'),
      skill('sw-p-8', 'Unit testing'),
      skill('sw-p-9', 'Integration testing'),
      skill('sw-p-10', 'Code review'),
      skill('sw-p-11', 'CI/CD fundamentals'),
      skill('sw-p-12', 'Agile development'),
      skill('sw-p-13', 'Documentation'),
      skill('sw-a-1', 'System design'),
      skill('sw-a-2', 'Distributed systems'),
      skill('sw-a-3', 'Microservices'),
      skill('sw-a-4', 'Advanced database design'),
      skill('sw-a-5', 'Performance optimization'),
      skill('sw-a-6', 'Scalability'),
      skill('sw-a-7', 'Software architecture'),
      skill('sw-a-8', 'Design patterns'),
      skill('sw-a-9', 'Advanced testing'),
      skill('sw-a-10', 'Security in software development'),
      skill('sw-a-11', 'Cloud-native development'),
      skill('sw-a-12', 'Observability'),
      skill('sw-a-13', 'Technical decision making'),
      skill('sw-l-1', 'Software architecture strategy'),
      skill('sw-l-2', 'Technical roadmap development'),
      skill('sw-l-3', 'Engineering standards'),
      skill('sw-l-4', 'Architecture governance'),
      skill('sw-l-5', 'Technical debt management'),
      skill('sw-l-6', 'Engineering team leadership'),
      skill('sw-l-7', 'Technology evaluation'),
      skill('sw-l-8', 'System scalability strategy'),
      skill('sw-l-9', 'Engineering performance management'),
      skill('sw-l-10', 'Technical mentoring'),
    ],
  },
  {
    id: 'cat-cloud',
    name: 'Cloud, Systems & DevOps',
    description:
      'Strengthen cloud platforms, automation, reliability, and infrastructure operations.',
    isMapped: true,
    skills: [
      skill('cloud-f-1', 'Computer systems fundamentals'),
      skill('cloud-f-2', 'Linux'),
      skill('cloud-f-3', 'Networking fundamentals'),
      skill('cloud-f-4', 'Operating systems'),
      skill('cloud-f-5', 'Virtualization'),
      skill('cloud-f-6', 'Cloud computing fundamentals'),
      skill('cloud-f-7', 'Cloud service models'),
      skill('cloud-f-8', 'Git'),
      skill('cloud-f-9', 'Basic scripting'),
      skill('cloud-f-10', 'System administration'),
      skill('cloud-p-1', 'AWS/Azure fundamentals'),
      skill('cloud-p-2', 'Cloud infrastructure'),
      skill('cloud-p-3', 'Docker'),
      skill('cloud-p-4', 'CI/CD'),
      skill('cloud-p-5', 'Infrastructure as Code'),
      skill('cloud-p-6', 'Server management'),
      skill('cloud-p-7', 'Cloud networking'),
      skill('cloud-p-8', 'Cloud storage'),
      skill('cloud-p-9', 'Database deployment'),
      skill('cloud-p-10', 'Monitoring'),
      skill('cloud-p-11', 'Logging'),
      skill('cloud-p-12', 'Backup and recovery'),
      skill('cloud-a-1', 'Kubernetes'),
      skill('cloud-a-2', 'Cloud architecture'),
      skill('cloud-a-3', 'High availability'),
      skill('cloud-a-4', 'Scalability'),
      skill('cloud-a-5', 'Infrastructure automation'),
      skill('cloud-a-6', 'Advanced CI/CD'),
      skill('cloud-a-7', 'Advanced Infrastructure as Code'),
      skill('cloud-a-8', 'Site reliability engineering'),
      skill('cloud-a-9', 'Observability'),
      skill('cloud-a-10', 'Disaster recovery'),
      skill('cloud-a-11', 'Cloud security'),
      skill('cloud-a-12', 'Performance optimization'),
      skill('cloud-a-13', 'Multi-cloud architecture'),
      skill('cloud-l-1', 'Cloud strategy'),
      skill('cloud-l-2', 'Enterprise cloud architecture'),
      skill('cloud-l-3', 'Cloud migration strategy'),
      skill('cloud-l-4', 'DevOps transformation'),
      skill('cloud-l-5', 'SRE strategy'),
      skill('cloud-l-6', 'Cloud cost optimization'),
      skill('cloud-l-7', 'Infrastructure governance'),
      skill('cloud-l-8', 'Technology architecture'),
      skill('cloud-l-9', 'Platform engineering'),
      skill('cloud-l-10', 'Technical team leadership'),
    ],
  },
  {
    id: 'cat-infra',
    name: 'IT Infrastructure & Network Engineering',
    description:
      'Advance networking, data center, and enterprise infrastructure capabilities.',
    isMapped: true,
    skills: [
      skill('infra-f-1', 'Networking fundamentals'),
      skill('infra-f-2', 'TCP/IP'),
      skill('infra-f-3', 'OSI model'),
      skill('infra-f-4', 'LAN/WAN'),
      skill('infra-f-5', 'IP addressing'),
      skill('infra-f-6', 'Subnetting'),
      skill('infra-f-7', 'Routing'),
      skill('infra-f-8', 'Switching'),
      skill('infra-f-9', 'Network devices'),
      skill('infra-f-10', 'Network troubleshooting'),
      skill('infra-f-11', 'Basic server infrastructure'),
      skill('infra-p-1', 'Enterprise networking'),
      skill('infra-p-2', 'VLANs'),
      skill('infra-p-3', 'Routing protocols'),
      skill('infra-p-4', 'Network security'),
      skill('infra-p-5', 'Wireless networks'),
      skill('infra-p-6', 'VPN'),
      skill('infra-p-7', 'Firewalls'),
      skill('infra-p-8', 'Network monitoring'),
      skill('infra-p-9', 'Network configuration'),
      skill('infra-p-10', 'Data center infrastructure'),
      skill('infra-p-11', 'Network documentation'),
      skill('infra-a-1', 'Enterprise network architecture'),
      skill('infra-a-2', 'Advanced routing'),
      skill('infra-a-3', 'Network automation'),
      skill('infra-a-4', 'SD-WAN'),
      skill('infra-a-5', 'Network virtualization'),
      skill('infra-a-6', 'High availability'),
      skill('infra-a-7', 'Data center networking'),
      skill('infra-a-8', 'Network performance optimization'),
      skill('infra-a-9', 'Infrastructure security'),
      skill('infra-a-10', 'Disaster recovery'),
      skill('infra-a-11', 'Network capacity planning'),
      skill('infra-l-1', 'Enterprise infrastructure strategy'),
      skill('infra-l-2', 'Network architecture governance'),
      skill('infra-l-3', 'Infrastructure planning'),
      skill('infra-l-4', 'Technology evaluation'),
      skill('infra-l-5', 'Infrastructure budgeting'),
      skill('infra-l-6', 'Large-scale deployment management'),
      skill('infra-l-7', 'Vendor management'),
      skill('infra-l-8', 'Network transformation'),
      skill('infra-l-9', 'Infrastructure risk management'),
      skill('infra-l-10', 'Technical team leadership'),
    ],
  },
  {
    id: 'cat-cyber',
    name: 'Cybersecurity',
    description:
      'Build security operations, threat defense, and cybersecurity governance skills.',
    isMapped: true,
    skills: [
      skill('cyber-f-1', 'Cybersecurity fundamentals'),
      skill('cyber-f-2', 'CIA triad'),
      skill('cyber-f-3', 'Threats and vulnerabilities'),
      skill('cyber-f-4', 'Network security fundamentals'),
      skill('cyber-f-5', 'Authentication'),
      skill('cyber-f-6', 'Access control'),
      skill('cyber-f-7', 'Password security'),
      skill('cyber-f-8', 'Security policies'),
      skill('cyber-f-9', 'Basic risk management'),
      skill('cyber-f-10', 'Security awareness'),
      skill('cyber-p-1', 'Vulnerability management'),
      skill('cyber-p-2', 'Security monitoring'),
      skill('cyber-p-3', 'Incident response'),
      skill('cyber-p-4', 'Endpoint security'),
      skill('cyber-p-5', 'Network security'),
      skill('cyber-p-6', 'Identity and access management'),
      skill('cyber-p-7', 'Security operations'),
      skill('cyber-p-8', 'Security testing'),
      skill('cyber-p-9', 'Security tools'),
      skill('cyber-p-10', 'Log analysis'),
      skill('cyber-p-11', 'Security documentation'),
      skill('cyber-p-12', 'Security compliance'),
      skill('cyber-a-1', 'Security architecture'),
      skill('cyber-a-2', 'Penetration testing'),
      skill('cyber-a-3', 'Threat hunting'),
      skill('cyber-a-4', 'Digital forensics'),
      skill('cyber-a-5', 'Cloud security'),
      skill('cyber-a-6', 'Application security'),
      skill('cyber-a-7', 'Security automation'),
      skill('cyber-a-8', 'SIEM'),
      skill('cyber-a-9', 'Zero Trust'),
      skill('cyber-a-10', 'Security risk assessment'),
      skill('cyber-a-11', 'Incident investigation'),
      skill('cyber-a-12', 'Advanced threat detection'),
      skill('cyber-l-1', 'Cybersecurity strategy'),
      skill('cyber-l-2', 'Enterprise security architecture'),
      skill('cyber-l-3', 'Security governance'),
      skill('cyber-l-4', 'Cybersecurity risk management'),
      skill('cyber-l-5', 'Security policies and standards'),
      skill('cyber-l-6', 'Incident management leadership'),
      skill('cyber-l-7', 'Security compliance'),
      skill('cyber-l-8', 'Business continuity'),
      skill('cyber-l-9', 'Security transformation'),
      skill('cyber-l-10', 'Security team leadership'),
    ],
  },
  {
    id: 'cat-integration',
    name: 'Software Integration & Technical Support',
    description:
      'Improve system integration, troubleshooting, and technical support excellence.',
    isMapped: true,
    skills: [
      skill('int-f-1', 'Computer and software fundamentals'),
      skill('int-f-2', 'Troubleshooting'),
      skill('int-f-3', 'Operating systems'),
      skill('int-f-4', 'Networking basics'),
      skill('int-f-5', 'Databases'),
      skill('int-f-6', 'APIs'),
      skill('int-f-7', 'Technical documentation'),
      skill('int-f-8', 'Ticket management'),
      skill('int-f-9', 'Customer communication', soft),
      skill('int-f-10', 'Incident management'),
      skill('int-p-1', 'System integration'),
      skill('int-p-2', 'API integration'),
      skill('int-p-3', 'REST APIs'),
      skill('int-p-4', 'Authentication'),
      skill('int-p-5', 'Database integration'),
      skill('int-p-6', 'Middleware'),
      skill('int-p-7', 'Application troubleshooting'),
      skill('int-p-8', 'Log analysis'),
      skill('int-p-9', 'Root cause analysis'),
      skill('int-p-10', 'Service monitoring'),
      skill('int-p-11', 'SLA management'),
      skill('int-p-12', 'IT service management'),
      skill('int-p-13', 'Customer support', soft),
      skill('int-a-1', 'Enterprise integration'),
      skill('int-a-2', 'Integration architecture'),
      skill('int-a-3', 'Microservices integration'),
      skill('int-a-4', 'API management'),
      skill('int-a-5', 'Event-driven architecture'),
      skill('int-a-6', 'Advanced troubleshooting'),
      skill('int-a-7', 'Performance troubleshooting'),
      skill('int-a-8', 'System reliability'),
      skill('int-a-9', 'Automation'),
      skill('int-a-10', 'Integration security'),
      skill('int-a-11', 'Disaster recovery'),
      skill('int-a-12', 'Problem management'),
      skill('int-l-1', 'Integration strategy'),
      skill('int-l-2', 'Enterprise architecture'),
      skill('int-l-3', 'Service management strategy'),
      skill('int-l-4', 'ITIL practices'),
      skill('int-l-5', 'Service-level governance'),
      skill('int-l-6', 'Technical support management'),
      skill('int-l-7', 'Customer success strategy'),
      skill('int-l-8', 'Incident management leadership'),
      skill('int-l-9', 'Service improvement'),
      skill('int-l-10', 'Technical team leadership'),
    ],
  },
  {
    id: 'cat-qa',
    name: 'QA, Testing & Quality Management',
    description:
      'Develop quality assurance, test automation, and continuous quality practices.',
    isMapped: true,
    skills: [
      skill('qa-1', 'Testing fundamentals'),
      skill('qa-2', 'Test case design'),
      skill('qa-3', 'Manual testing'),
      skill('qa-4', 'Automation testing'),
      skill('qa-5', 'API testing'),
      skill('qa-6', 'Performance testing'),
      skill('qa-7', 'Quality metrics'),
      skill('qa-8', 'CI test pipelines'),
    ],
  },
  {
    id: 'cat-uiux',
    name: 'UI/UX & Design',
    description:
      'Grow research, interaction design, visual design, and design systems craft.',
    isMapped: true,
    skills: [
      skill('ux-1', 'User research', soft),
      skill('ux-2', 'Wireframing', soft),
      skill('ux-3', 'Prototyping', soft),
      skill('ux-4', 'Interaction design', soft),
      skill('ux-5', 'Visual design', soft),
      skill('ux-6', 'Design systems', soft),
      skill('ux-7', 'Usability testing', soft),
      skill('ux-8', 'Accessibility', soft),
    ],
  },
  {
    id: 'cat-presales',
    name: 'Presales, Solutions & Technical Consulting',
    description:
      'Build solution consulting, demos, and technical sales enablement skills.',
    isMapped: true,
    skills: [
      skill('ps-1', 'Solution discovery', soft),
      skill('ps-2', 'Demo delivery', soft),
      skill('ps-3', 'RFP response', soft),
      skill('ps-4', 'Architecture pitching'),
      skill('ps-5', 'Competitive analysis', soft),
      skill('ps-6', 'Proof of concept'),
      skill('ps-7', 'Customer workshops', soft),
      skill('ps-8', 'Technical storytelling', soft),
    ],
  },
  {
    id: 'cat-sales',
    name: 'Sales, Business Development & Marketing',
    description:
      'Strengthen pipeline, customer engagement, and go-to-market execution skills.',
    isMapped: true,
    skills: [
      skill('sales-1', 'Prospecting', soft),
      skill('sales-2', 'Discovery calls', soft),
      skill('sales-3', 'Negotiation', soft),
      skill('sales-4', 'Account management', soft),
      skill('sales-5', 'Channel partnerships', soft),
      skill('sales-6', 'Campaign planning', soft),
      skill('sales-7', 'Pipeline forecasting', soft),
      skill('sales-8', 'Customer retention', soft),
    ],
  },
  {
    id: 'cat-finance',
    name: 'Finance, Accounting & Revenue Operations',
    description:
      'Develop accounting, financial analysis, and revenue operations capabilities.',
    isMapped: true,
    skills: [
      skill('fin-1', 'Financial accounting', soft),
      skill('fin-2', 'Budgeting', soft),
      skill('fin-3', 'Financial reporting', soft),
      skill('fin-4', 'Cash flow management', soft),
      skill('fin-5', 'Revenue recognition', soft),
      skill('fin-6', 'Cost analysis', soft),
      skill('fin-7', 'Treasury basics', soft),
      skill('fin-8', 'Audit readiness', soft),
    ],
  },
  {
    id: 'cat-hr',
    name: 'People, HR, Administration & Organizational Development',
    description:
      'Build HR operations, talent, employee relations, and organizational development skills.',
    isMapped: true,
    skills: [
      skill('hr-1', 'Recruiting fundamentals', soft),
      skill('hr-2', 'Onboarding', soft),
      skill('hr-3', 'Performance coaching', soft),
      skill('hr-4', 'Employee relations', soft),
      skill('hr-5', 'Compensation basics', soft),
      skill('hr-6', 'Learning & development', soft),
      skill('hr-7', 'HR policy', soft),
      skill('hr-8', 'Organizational development', soft),
    ],
  },
  {
    id: 'cat-ops',
    name: 'Operations, Supply Chain, Facilities & Support Services',
    description:
      'Improve sourcing, logistics, facilities, and day-to-day operational support skills.',
    isMapped: true,
    skills: [
      skill('ops-1', 'Procurement basics', soft),
      skill('ops-2', 'Inventory management', soft),
      skill('ops-3', 'Logistics coordination', soft),
      skill('ops-4', 'Vendor management', soft),
      skill('ops-5', 'Facilities operations', soft),
      skill('ops-6', 'Fleet coordination', soft),
      skill('ops-7', 'Service level tracking', soft),
      skill('ops-8', 'Process improvement', soft),
    ],
  },
];

(() => {
  const product = GROWTH_PLAN_TAXONOMY_SEED.find((c) => c.id === 'cat-product');
  if (!product) return;

  const youtubeSkill = product.skills.find((s) => s.id === 'pm-f-1');
  if (youtubeSkill) {
    youtubeSkill.resources = [
      {
        id: 'res-pm-yt-1',
        title: 'Intro to product discovery',
        type: 'youtube',
        url: 'https://www.youtube.com/watch?v=y8OnoxKotPQ',
        videoId: 'y8OnoxKotPQ',
      },
    ];
  }

  const vimeoSkill = product.skills.find((s) => s.id === 'pm-f-2');
  if (vimeoSkill) {
    vimeoSkill.resources = [
      {
        id: 'res-pm-vimeo-1',
        title: 'Project kickoff walkthrough',
        type: 'link',
        url: 'https://vimeo.com/76979871',
      },
    ];
  }

  const courseSkill = product.skills.find((s) => s.id === 'pm-f-3');
  if (courseSkill) {
    // courseId is resolved against the live TNA catalog on the skill page
    // (falls back to the first published course when this seed id is absent).
    courseSkill.resources = [
      {
        id: 'res-pm-course-1',
        title: 'TNA course',
        type: 'course',
        url: '/tna/management',
        courseId: null,
        courseName: 'TNA course',
      },
    ];
  }

  const docSkill = product.skills.find((s) => s.id === 'pm-f-9');
  if (docSkill) {
    docSkill.resources = [
      {
        id: 'res-pm-doc-1',
        title: 'Documentation best practices (PDF)',
        type: 'document',
        url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
      },
    ];
  }
})();
