import {
  PrototypeAuditEvent,
  PrototypeAuditPerson,
} from './types';

export const MOCK_AUDIT_PEOPLE = {
  wongel: {
    id: 'user-wongel',
    firstName: 'Wongel',
    lastName: 'Wondyifraw',
    role: 'HR Manager',
  },
  abel: {
    id: 'user-abel',
    firstName: 'Abel',
    lastName: 'Tesfaye',
    role: 'Software Engineer',
  },
  meron: {
    id: 'user-meron',
    firstName: 'Meron',
    lastName: 'Alemu',
    role: 'Payroll Admin',
  },
  dawit: {
    id: 'user-dawit',
    firstName: 'Dawit',
    lastName: 'Bekele',
    role: 'Department Lead',
  },
  hanna: {
    id: 'user-hanna',
    firstName: 'Hanna',
    lastName: 'Gebre',
    role: 'Recruiter',
  },
  kidus: {
    id: 'user-kidus',
    firstName: 'Kidus',
    lastName: 'Haile',
    role: 'Finance Officer',
  },
  selam: {
    id: 'user-selam',
    firstName: 'Selam',
    lastName: 'Tadesse',
    role: 'Employee',
  },
  yared: {
    id: 'user-yared',
    firstName: 'Yared',
    lastName: 'Mekonnen',
    role: 'OKR Champion',
  },
  helen: {
    id: 'user-helen',
    firstName: 'Helen',
    lastName: 'Assefa',
    role: 'Attendance Officer',
  },
  nahom: {
    id: 'user-nahom',
    firstName: 'Nahom',
    lastName: 'Kebede',
    role: 'System Admin',
  },
} as const satisfies Record<string, PrototypeAuditPerson>;

const session = (
  id: string,
  ip = '196.188.42.17',
  geo = 'Addis Ababa, ET',
  browser = 'Chrome 126',
  os = 'Windows 11',
) => ({
  ipAddress: ip,
  geoLocation: geo,
  browser,
  os,
  sessionId: id,
});

export const MOCK_AUDIT_EVENTS: PrototypeAuditEvent[] = [
  {
    id: 'EVT-10021',
    eventId: 'EVT-10021',
    performedAt: '2026-08-12T11:32:00.000Z',
    severity: 'CRITICAL',
    actor: MOCK_AUDIT_PEOPLE.wongel,
    target: MOCK_AUDIT_PEOPLE.abel,
    actionVerb: 'updated',
    fieldOrResource: 'Salary',
    module: 'PayrollAuditLog',
    moduleLabel: 'Payroll',
    ...session('sess_8f3a21c9'),
    changes: [
      {
        field: 'Salary',
        previous: '18500',
        next: '24000',
        sensitive: true,
      },
      {
        field: 'Effective Date',
        previous: '2026-01-01',
        next: '2026-08-01',
      },
    ],
  },
  {
    id: 'EVT-10020',
    eventId: 'EVT-10020',
    performedAt: '2026-08-12T09:15:00.000Z',
    severity: 'CRITICAL',
    actor: MOCK_AUDIT_PEOPLE.meron,
    target: MOCK_AUDIT_PEOPLE.abel,
    actionVerb: 'updated',
    fieldOrResource: 'Bank Account',
    module: 'PayrollAuditLog',
    moduleLabel: 'Payroll',
    ...session('sess_1c90ab44', '196.188.18.90'),
    changes: [
      {
        field: 'Bank Account',
        previous: '1000123456789',
        next: '1000987654321',
        sensitive: true,
      },
      {
        field: 'Bank Name',
        previous: 'CBE',
        next: 'Awash Bank',
      },
    ],
  },
  {
    id: 'EVT-10019',
    eventId: 'EVT-10019',
    performedAt: '2026-08-11T16:40:00.000Z',
    severity: 'HIGH',
    actor: MOCK_AUDIT_PEOPLE.dawit,
    target: MOCK_AUDIT_PEOPLE.abel,
    actionVerb: 'updated',
    fieldOrResource: 'Department',
    module: 'OrgAndEmpAuditLog',
    moduleLabel: 'Employee Management',
    ...session('sess_77b12e01'),
    changes: [
      {
        field: 'Department',
        previous: 'Support',
        next: 'Engineering',
      },
      {
        field: 'Branch',
        previous: 'Bole',
        next: 'HQ',
      },
    ],
  },
  {
    id: 'EVT-10018',
    eventId: 'EVT-10018',
    performedAt: '2026-08-11T14:05:00.000Z',
    severity: 'HIGH',
    actor: MOCK_AUDIT_PEOPLE.wongel,
    target: MOCK_AUDIT_PEOPLE.selam,
    actionVerb: 'updated',
    fieldOrResource: 'Job Title',
    module: 'OrgAndEmpAuditLog',
    moduleLabel: 'Employee Management',
    ...session('sess_a91f30d2'),
    changes: [
      {
        field: 'Job Title',
        previous: 'Junior Officer',
        next: 'Officer',
      },
    ],
  },
  {
    id: 'EVT-10017',
    eventId: 'EVT-10017',
    performedAt: '2026-08-11T10:22:00.000Z',
    severity: 'MEDIUM',
    actor: MOCK_AUDIT_PEOPLE.helen,
    target: MOCK_AUDIT_PEOPLE.abel,
    actionVerb: 'updated',
    fieldOrResource: 'Work Schedule',
    module: 'TimesheetAuditLog',
    moduleLabel: 'Time and attendance',
    ...session('sess_c3e88110', '197.156.64.22', 'Addis Ababa, ET', 'Edge 125', 'Windows 11'),
    changes: [
      {
        field: 'Work Schedule',
        previous: 'Standard 8:30–17:30',
        next: 'Flexible 9:00–18:00',
      },
    ],
  },
  {
    id: 'EVT-10016',
    eventId: 'EVT-10016',
    performedAt: '2026-08-10T15:48:00.000Z',
    severity: 'MEDIUM',
    actor: MOCK_AUDIT_PEOPLE.helen,
    target: MOCK_AUDIT_PEOPLE.kidus,
    actionVerb: 'updated',
    fieldOrResource: 'Shift',
    module: 'TimesheetAuditLog',
    moduleLabel: 'Time and attendance',
    ...session('sess_d44aa901'),
    changes: [
      {
        field: 'Shift',
        previous: 'Morning',
        next: 'Afternoon',
      },
    ],
  },
  {
    id: 'EVT-10015',
    eventId: 'EVT-10015',
    performedAt: '2026-08-10T08:12:00.000Z',
    severity: 'INFO',
    actor: MOCK_AUDIT_PEOPLE.nahom,
    target: MOCK_AUDIT_PEOPLE.abel,
    actionVerb: 'created',
    fieldOrResource: 'User Account',
    module: 'OrgAndEmpAuditLog',
    moduleLabel: 'Employee Management',
    ...session('sess_0ab33e77', '10.0.12.4', 'Internal Network', 'Chrome 126', 'macOS 14'),
    changes: [
      {
        field: 'Status',
        previous: '--',
        next: 'Active',
      },
      {
        field: 'Email',
        previous: '--',
        next: 'abel.tesfaye@company.com',
      },
    ],
  },
  {
    id: 'EVT-10014',
    eventId: 'EVT-10014',
    performedAt: '2026-08-09T13:30:00.000Z',
    severity: 'INFO',
    actor: MOCK_AUDIT_PEOPLE.hanna,
    target: MOCK_AUDIT_PEOPLE.yared,
    actionVerb: 'created',
    fieldOrResource: 'Candidate Profile',
    module: 'RecruitmentAuditLog',
    moduleLabel: 'Talent Acquisition',
    ...session('sess_b21c0098'),
    changes: [
      {
        field: 'Stage',
        previous: '--',
        next: 'Sourced',
      },
    ],
  },
  {
    id: 'EVT-10013',
    eventId: 'EVT-10013',
    performedAt: '2026-08-09T11:05:00.000Z',
    severity: 'MEDIUM',
    actor: MOCK_AUDIT_PEOPLE.hanna,
    target: MOCK_AUDIT_PEOPLE.yared,
    actionVerb: 'updated',
    fieldOrResource: 'Interview Status',
    module: 'RecruitmentAuditLog',
    moduleLabel: 'Talent Acquisition',
    ...session('sess_b21c0099'),
    changes: [
      {
        field: 'Interview Status',
        previous: 'Scheduled',
        next: 'Completed',
      },
    ],
  },
  {
    id: 'EVT-10012',
    eventId: 'EVT-10012',
    performedAt: '2026-08-08T17:20:00.000Z',
    severity: 'HIGH',
    actor: MOCK_AUDIT_PEOPLE.hanna,
    target: MOCK_AUDIT_PEOPLE.selam,
    actionVerb: 'deleted',
    fieldOrResource: 'Application',
    module: 'RecruitmentAuditLog',
    moduleLabel: 'Talent Acquisition',
    ...session('sess_ee12c4a0'),
    changes: [
      {
        field: 'Application',
        previous: 'In Progress',
        next: 'Withdrawn',
      },
    ],
  },
  {
    id: 'EVT-10011',
    eventId: 'EVT-10011',
    performedAt: '2026-08-08T09:44:00.000Z',
    severity: 'INFO',
    actor: MOCK_AUDIT_PEOPLE.yared,
    target: MOCK_AUDIT_PEOPLE.abel,
    actionVerb: 'updated',
    fieldOrResource: 'OKR Progress',
    module: 'OKRAuditLog',
    moduleLabel: 'OKR',
    ...session('sess_91aa2201', '196.188.42.17', 'Addis Ababa, ET', 'Firefox 128', 'Ubuntu 24.04'),
    changes: [
      {
        field: 'Progress',
        previous: '40%',
        next: '65%',
      },
    ],
  },
  {
    id: 'EVT-10010',
    eventId: 'EVT-10010',
    performedAt: '2026-08-07T15:10:00.000Z',
    severity: 'MEDIUM',
    actor: MOCK_AUDIT_PEOPLE.yared,
    target: MOCK_AUDIT_PEOPLE.dawit,
    actionVerb: 'updated',
    fieldOrResource: 'Key Result',
    module: 'OKRAuditLog',
    moduleLabel: 'OKR',
    ...session('sess_91aa2202'),
    changes: [
      {
        field: 'Key Result Target',
        previous: '80',
        next: '90',
      },
    ],
  },
  {
    id: 'EVT-10009',
    eventId: 'EVT-10009',
    performedAt: '2026-08-07T12:00:00.000Z',
    severity: 'INFO',
    actor: MOCK_AUDIT_PEOPLE.dawit,
    target: MOCK_AUDIT_PEOPLE.abel,
    actionVerb: 'created',
    fieldOrResource: 'Feedback',
    module: 'CFRAuditLog',
    moduleLabel: 'CFR',
    ...session('sess_55c10d88'),
    changes: [
      {
        field: 'Feedback Type',
        previous: '--',
        next: 'Recognition',
      },
    ],
  },
  {
    id: 'EVT-10008',
    eventId: 'EVT-10008',
    performedAt: '2026-08-06T10:18:00.000Z',
    severity: 'MEDIUM',
    actor: MOCK_AUDIT_PEOPLE.wongel,
    target: MOCK_AUDIT_PEOPLE.abel,
    actionVerb: 'updated',
    fieldOrResource: 'Training Plan',
    module: 'TNAAuditLog',
    moduleLabel: 'Learning & Growth',
    ...session('sess_6f90bb21'),
    changes: [
      {
        field: 'Training Plan',
        previous: 'Not assigned',
        next: 'Leadership Q3',
      },
    ],
  },
  {
    id: 'EVT-10007',
    eventId: 'EVT-10007',
    performedAt: '2026-08-06T08:50:00.000Z',
    severity: 'HIGH',
    actor: MOCK_AUDIT_PEOPLE.kidus,
    target: MOCK_AUDIT_PEOPLE.abel,
    actionVerb: 'updated',
    fieldOrResource: 'TIN',
    module: 'PayrollAuditLog',
    moduleLabel: 'Payroll',
    ...session('sess_cc0193aa'),
    changes: [
      {
        field: 'TIN',
        previous: '0045123490',
        next: '0045123498',
        sensitive: true,
      },
    ],
  },
  {
    id: 'EVT-10006',
    eventId: 'EVT-10006',
    performedAt: '2026-08-05T16:25:00.000Z',
    severity: 'CRITICAL',
    actor: MOCK_AUDIT_PEOPLE.meron,
    target: MOCK_AUDIT_PEOPLE.kidus,
    actionVerb: 'updated',
    fieldOrResource: 'Basic Salary',
    module: 'PayrollAuditLog',
    moduleLabel: 'Payroll',
    ...session('sess_9e11d045'),
    changes: [
      {
        field: 'Basic Salary',
        previous: '22000',
        next: '27500',
        sensitive: true,
      },
    ],
  },
  {
    id: 'EVT-10005',
    eventId: 'EVT-10005',
    performedAt: '2026-08-05T07:40:00.000Z',
    severity: 'INFO',
    actor: MOCK_AUDIT_PEOPLE.helen,
    target: MOCK_AUDIT_PEOPLE.selam,
    actionVerb: 'created',
    fieldOrResource: 'Attendance Record',
    module: 'TimesheetAuditLog',
    moduleLabel: 'Time and attendance',
    ...session('sess_aa1001c2'),
    changes: [
      {
        field: 'Check-in',
        previous: '--',
        next: '08:32',
      },
    ],
  },
  {
    id: 'EVT-10004',
    eventId: 'EVT-10004',
    performedAt: '2026-08-04T14:55:00.000Z',
    severity: 'MEDIUM',
    actor: MOCK_AUDIT_PEOPLE.wongel,
    target: MOCK_AUDIT_PEOPLE.abel,
    actionVerb: 'updated',
    fieldOrResource: 'Role Permission',
    module: 'OrgAndEmpAuditLog',
    moduleLabel: 'Employee Management',
    ...session('sess_f13bb870'),
    changes: [
      {
        field: 'Role',
        previous: 'Employee',
        next: 'Employee + OKR Contributor',
      },
    ],
  },
  {
    id: 'EVT-10003',
    eventId: 'EVT-10003',
    performedAt: '2026-08-04T11:12:00.000Z',
    severity: 'HIGH',
    actor: MOCK_AUDIT_PEOPLE.nahom,
    target: MOCK_AUDIT_PEOPLE.selam,
    actionVerb: 'updated',
    fieldOrResource: 'Employment Status',
    module: 'OrgAndEmpAuditLog',
    moduleLabel: 'Employee Management',
    ...session('sess_f13bb871'),
    changes: [
      {
        field: 'Employment Status',
        previous: 'Probation',
        next: 'Active',
      },
    ],
  },
  {
    id: 'EVT-10002',
    eventId: 'EVT-10002',
    performedAt: '2026-08-03T09:30:00.000Z',
    severity: 'INFO',
    actor: MOCK_AUDIT_PEOPLE.yared,
    target: MOCK_AUDIT_PEOPLE.hanna,
    actionVerb: 'created',
    fieldOrResource: 'Objective',
    module: 'OKRAuditLog',
    moduleLabel: 'OKR',
    ...session('sess_33d0aa11'),
    changes: [
      {
        field: 'Objective',
        previous: '--',
        next: 'Improve hiring SLA',
      },
    ],
  },
  {
    id: 'EVT-10001',
    eventId: 'EVT-10001',
    performedAt: '2026-08-03T08:05:00.000Z',
    severity: 'MEDIUM',
    actor: MOCK_AUDIT_PEOPLE.kidus,
    target: MOCK_AUDIT_PEOPLE.abel,
    actionVerb: 'updated',
    fieldOrResource: 'Allowance',
    module: 'PayrollAuditLog',
    moduleLabel: 'Payroll',
    ...session('sess_44e1bb22'),
    changes: [
      {
        field: 'Transport Allowance',
        previous: '800',
        next: '1200',
      },
    ],
  },
  {
    id: 'EVT-10000',
    eventId: 'EVT-10000',
    performedAt: '2026-08-02T13:18:00.000Z',
    severity: 'HIGH',
    actor: MOCK_AUDIT_PEOPLE.wongel,
    target: MOCK_AUDIT_PEOPLE.dawit,
    actionVerb: 'updated',
    fieldOrResource: 'Contract Type',
    module: 'OrgAndEmpAuditLog',
    moduleLabel: 'Employee Management',
    ...session('sess_55f2cc33'),
    changes: [
      {
        field: 'Contract Type',
        previous: 'Fixed term',
        next: 'Permanent',
      },
    ],
  },
  {
    id: 'EVT-09999',
    eventId: 'EVT-09999',
    performedAt: '2026-08-02T07:22:00.000Z',
    severity: 'INFO',
    actor: MOCK_AUDIT_PEOPLE.helen,
    target: MOCK_AUDIT_PEOPLE.abel,
    actionVerb: 'updated',
    fieldOrResource: 'Check-in Time',
    module: 'TimesheetAuditLog',
    moduleLabel: 'Time and attendance',
    ...session('sess_66a3dd44'),
    changes: [
      {
        field: 'Check-in Time',
        previous: '08:45',
        next: '08:30',
      },
    ],
  },
  {
    id: 'EVT-09998',
    eventId: 'EVT-09998',
    performedAt: '2026-07-31T15:40:00.000Z',
    severity: 'MEDIUM',
    actor: MOCK_AUDIT_PEOPLE.meron,
    target: MOCK_AUDIT_PEOPLE.abel,
    actionVerb: 'updated',
    fieldOrResource: 'Pay Period',
    module: 'PayrollAuditLog',
    moduleLabel: 'Payroll',
    ...session('sess_77b4ee55'),
    changes: [
      {
        field: 'Pay Period',
        previous: 'Monthly',
        next: 'Semi-monthly',
      },
    ],
  },
  {
    id: 'EVT-09997',
    eventId: 'EVT-09997',
    performedAt: '2026-07-30T12:15:00.000Z',
    severity: 'HIGH',
    actor: MOCK_AUDIT_PEOPLE.hanna,
    target: MOCK_AUDIT_PEOPLE.yared,
    actionVerb: 'updated',
    fieldOrResource: 'Offer Letter',
    module: 'RecruitmentAuditLog',
    moduleLabel: 'Talent Acquisition',
    ...session('sess_88c5ff66'),
    changes: [
      {
        field: 'Offer Status',
        previous: 'Draft',
        next: 'Sent',
      },
      {
        field: 'Proposed Salary',
        previous: '20000',
        next: '21000',
        sensitive: true,
      },
    ],
  },
  {
    id: 'EVT-09996',
    eventId: 'EVT-09996',
    performedAt: '2026-07-29T10:00:00.000Z',
    severity: 'INFO',
    actor: MOCK_AUDIT_PEOPLE.abel,
    target: MOCK_AUDIT_PEOPLE.abel,
    actionVerb: 'updated',
    fieldOrResource: 'Emergency Contact',
    module: 'OrgAndEmpAuditLog',
    moduleLabel: 'Employee Management',
    ...session('sess_99d60077', '196.188.50.11', 'Addis Ababa, ET', 'Chrome 126', 'Android 15'),
    changes: [
      {
        field: 'Emergency Contact',
        previous: 'Meron Alemu',
        next: 'Hanna Gebre',
      },
    ],
  },
  {
    id: 'EVT-09995',
    eventId: 'EVT-09995',
    performedAt: '2026-07-28T09:10:00.000Z',
    severity: 'MEDIUM',
    actor: MOCK_AUDIT_PEOPLE.nahom,
    target: MOCK_AUDIT_PEOPLE.wongel,
    actionVerb: 'updated',
    fieldOrResource: 'Role Permission',
    module: 'OrgAndEmpAuditLog',
    moduleLabel: 'Employee Management',
    ...session('sess_aae71188'),
    changes: [
      {
        field: 'Permission Group',
        previous: 'HR Officer',
        next: 'HR Manager',
      },
    ],
  },
];
